var situation_relation = {
    "早上起床": [
        ["Time to wake up!", "该起床了！"],
        ["Wake up, you sleepyhead.", "起床了，你这个贪睡鬼。"],
        ["Rise and shine.", "太阳都晒屁股了。"],
        ["I'll tickle you if you don't wake up.", "再不起床的话，我要抓痒痒了。"],
        ["Can I sleep some more?", "我可以多睡一会吗？"],
        ["I‘m so tired that I can‘t get up.", "我太累了，起不来。"],
        ["I‘ll count to three. Come on!", "我数到三，快点起床！"],
        ["You don't have to wake me up. I'm already up.", "你不用叫我也没关系。我已经醒了。"],
        ["Did you not hear the alarm?", "你没有听到闹钟吗？"],
        ["Don't doze off. Sit right up!", "不要打瞌睡了。做好！"]
    ],
    "机场": [
        ["I have to catch a connecting flight.", "我必须搭乘转机航班。"],
        ["Where can I get the boarding pass for MU flight?", "我在哪里可以获得MU航班的登机牌？"],
        ["Where can I get my baggage?", "在哪里可以领到我的行李？"]
    ],
    "出租车": [
        ["Take me to this address, please.", "请带我去到这个地址。"],
        ["How much does it cost to take a taxi to this address?", "乘出租车到这个地址需要多少钱？"],
        ["Anywhere around here is fine.", "到这附近的任何地方都可以。"],
        ["Keep the change.", "不用找零了。"]
    ],
    "酒店": [
        ["I would like to book a room.", "我想预订一个房间。"],
        ["I'd like a single room.", "我想要一间单人房。"],
        ["I'd like to book a double room for 3 nights.", "我想预订一间双人房3晚。"],
        ["How much is a double room per night?", "双人房每晚多少钱？"],
        ["I'd like a room with a nice view.", "我想要一个风景优美的房间。"],
        ["I'm arriving late. Please keep my reservation.", "我晚点了。 请保留我的预订。"],
        ["When is breakfast served?", "何时提供早餐？"],
        ["The bed sheets are dirty.", "床单很脏。"],
        ["I'd like to check out.", "我想退房。"]
    ],
    "餐厅": [
        ["A table for two, please.", "请找张桌子，2个人。"],
        ["We prefer to sit by the window.", "我们想坐在窗边。"],
        ["Do you have a menu in Chinese?", "你们有中文菜单吗？"],
        ["What is the most popular dish here?", "这里最受欢迎的菜是什么？"],
        ["Could I have the check, please?", "请给我账单好吗?"]
    ],
    "购物": [
        ["May I try this on?", "我可以试一下吗？"],
        ["Do I need to pay tax?", "我需要纳税吗？"],
        ["Can I pay by credit card?", "我可以用信用卡付款吗？"],
        ["It's too expensive.", "这太贵了。"],
        ["Can you come down a little bit?", "能稍微便宜点吗？"],
        ["Is this your final price?", "这是你的最终价格吗？"],
        ["I'd like one size up.", "我想要大一个尺码。"],
        ["I'll take this one.", "我就要这个了。"],
        ["Where is the cashier?", "收银员在哪里？"],
        ["Where can I change money.", "我可以在哪里换钱。"],
        ["Is there an ATM machine around here?", "这附近有自动取款机吗？"]
    ],
    "吵架必备": [
        ["You make me sick!", "你真让我恶心！"],
        ["What's wrong with you?", "你怎么回事？"],
        ["I'm very disappointed.", "真让我失望。"],
        ["You're a jerk!", "你是个废物/混球！"],
        ["Don't talk to me like that!", "别那样和我说话!"],
        ["Who do you think you are?", "你以为你是谁？"],
        ["What's your problem?", "你怎么回事啊？"],
        ["I hate you!", "我讨厌你！"],
        ["I don't want to see you again!", "我不愿再见到你！"],
        ["You're crazy!", "你疯了!"],
        ["Are you insane/crazy/out of your mind?", "你疯了吗？"],
        ["Don't bother me.", "别烦我。"],
        ["Knock it off.", "少来这一套。"],
        ["Get out of my face.", "从我面前消失！"],
        ["Leave me alone.", "走开。"],
        ["Get lost.", "滚开！"],
        ["Take a hike!", "哪儿凉快哪儿歇着去吧。"],
        ["You piss me off.", "你气死我了。"],
        ["It's none of your business.", "关你屁事！"],
        ["What's the meaning of this?", "这是什么意思？"],
        ["How dare you!", "你敢！"],
        ["Cut it out.", "省省吧。"],
        ["You stupid jerk!", "你这蠢货！"],
        ["You have a lot of nerve.", "脸皮真厚。"],
        ["I'm fed up.", "我厌倦了。"],
        ["I can't take it anymore.", "我受不了了！"],
        ["I've had enough of your garbage.", "我听腻了你的废话。"],
        ["Shut up!", "闭嘴！"],
        ["What do you want?", "你想怎么样？"],
        ["Do you know what time it is?", "你知道现在都几点吗？"],
        ["What were you thinking?", "你脑子进水啊？"],
        ["How can you say that?", "你怎么可以这样说？"],
        ["Who says?", "谁说的？"],
        ["That's what you think!", "那才是你脑子里想的！"],
        ["Don't look at me like that.", "别那样看着我。"],
        ["What did you say?", "你说什么？"],
        ["You are out of your mind.", "你脑子有毛病！"],
        ["You make me so mad.", "你气死我了啦。"],
        ["Drop dead.", "去死吧！"],
        ["Don't give me your excuses/ No more excuses.", "别找借口。"],
        ["Nonsense!", "鬼话！"],
        ["You're a pain in the ass.", "你这讨厌鬼。"],
        ["You're an asshole.", "你这缺德鬼。"],
        ["You asked for it.", "你自找的。"],
        ["Get over yourself.", "别自以为是。"],
        ["You're nothing to me.", "你对我什么都不是。"],
        ["It's not my fault.", "不是我的错。"],
        ["You look guilty.", "你看上去心虚。"],
        ["I can't help it.", "我没办法。"],
        ["That's your problem.", "那是你的问题。"],
        ["I don't want to hear it.", "我不想听！"],
        ["Get off my back.", "少跟我罗嗦。"],
        ["Give me a break.", "饶了我吧。"],
        ["Who do you think you're talking to?", "你以为你在跟谁说话？"],
        ["Look at this mess!", "看看这烂摊子！"],
        ["You're so careless.", "你真粗心。"],
        ["Why on earth didn't you tell me the truth?", "你到底为什么不跟我说实话？"],
        ["I'm about to explode!", "我肺都快要气炸了！"],
        ["What a stupid idiot!", "真是白痴一个！"],
        ["I'm not going to put up with this!", "我再也受不了啦！"],
        ["That's terrible.", "真糟糕！"],
        ["Just look at what you've done!", "看看你都做了些什么！"],
        ["I wish I had never met you.", "我真后悔这辈子遇到你！"],
        ["You're a disgrace.", "你真丢人！"],
        ["I'll never forgive you!", "我永远都不会饶恕你！"],
        ["Don't nag me!", "别在我面前唠叨！"],
        ["I'm sick of it.", "我都腻了。"],
        ["Don't you dare come back again!", "你敢再回来！"],
        ["Stop screwing/ fooling/ messing around!", "别鬼混了！"],
        ["Mind your own business!", "管好你自己的事！"],
        ["You're just a good for nothing bum!", "你真是一个废物！"],
        ["You've gone too far!", "你太过分了！"],
        ["I loathe you!", "我讨厌你！"],
        ["I detest you!", "我恨你！"],
        ["Get the hell out of here!", "滚开!"],
        ["Don't be that way!", "别那样！"],
        ["Can't you do anything right?", "成事不足，败事有余。"],
        ["You're impossible.", "你真不可救药。"],
        ["Don't touch me!", "别碰我！"],
        ["Get away from me!", "离我远一点儿！"],
        ["Get out of my life.", "从我的生活中消失吧。"],
        ["You're a joke!", "你真是一个小丑！"],
        ["Don't give me your attitude.", "别跟我摆架子。"],
        ["You'll be sorry.", "你会后悔的。"],
        ["We're through.", "我们完了！"],
        ["Look at the mess you've made!", "你搞得一团糟！"],
        ["You've ruined everything.", "全都让你搞砸了。"],
        ["I can't believe your never.", "你好大的胆子！"],
        ["You're away too far.", "你太过分了。"],
        ["I can't take you any more!", "我再也受不了你啦！"],
        ["I'm telling you for the last time!", "我最后再告诉你一次！"],
        ["I could kill you!", "我宰了你！"],
        ["That's the stupidest thing I've ever heard!", "那是我听到的最愚蠢的事！"],
        ["I can't believe a word you say.", "我才不信你呢!"],
        ["You never tell the truth！", "你从来就不说实话！"],
        ["Don't push me!", "别逼我！"],
        ["Enough is enough!", "适可而止！"]
    ]
};
