ted_info = [
    {'index': '1', 'start': 12, 'eng': 'When people find out I write about time management,', 'chn': '当人们发现我写关于时间管理的文章时，', 'end': 15},
    {'index': '2', 'start': 16, 'eng': 'they assume two things.', 'chn': '他们都会假设两件事：', 'end': 18},
    {'index': '3', 'start': 19, 'eng': "One is that I'm always on time,", 'chn': '第一，我永远都准时，', 'end': 22},
    {'index': '4', 'start': 23, 'eng': "and I'm not.", 'chn': '但我并不是。', 'end': 24},
    {'index': '5', 'start': 25, 'eng': 'I have four small children,', 'chn': '我有四个小孩，', 'end': 26},
    {'index': '6', 'start': 26, 'eng': 'and I would like to blame them for my occasional tardiness,', 'chn': '我偶尔将迟到归咎于他们，', 'end': 29},
    {'index': '7', 'start': 29, 'eng': "but sometimes it's just not their fault.", 'chn': '不过有时候真的不是因为他们。', 'end': 31},
    {'index': '8', 'start': 32, 'eng': 'I was once late to my own speech on time management.', 'chn': '我有一次在去我的一个关于时间管理的演讲时迟到了。', 'end': 34},
    {'index': '9', 'start': 34, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 35},
    {'index': '10', 'start': 36, 'eng': 'We all had to just take a moment together and savor that irony.', 'chn': '我们都需要一点时间去好好地体味一下这有多么讽刺。', 'end': 39},
    {'index': '11', 'start': 40, 'eng': 'The second thing they assume is that I have lots of tips and tricks', 'chn': '第二，人们总是假设我有很多关于', 'end': 44},
    {'index': '12', 'start': 44, 'eng': 'for saving bits of time here and there.', 'chn': '如何节省时间的贴士和技巧。', 'end': 45},
    {'index': '13', 'start': 45, 'eng': "Sometimes I'll hear from magazines that are doing a story along these lines,", 'chn': '有时候我听说一些杂志在写这方面的故事，', 'end': 49},
    {'index': '14', 'start': 49, 'eng': 'generally on how to help their readers find an extra hour in the day.', 'chn': '通常都是关于教读者如何在一天中获得额外一个小时。', 'end': 53},
    {'index': '15', 'start': 53, 'eng': "And the idea is that we'll shave bits of time off everyday activities,", 'chn': '基本思路就是从日常的每个活动中挤出一点时间，', 'end': 56},
    {'index': '16', 'start': 56, 'eng': 'add it up,', 'chn': '加起来，', 'end': 57},
    {'index': '17', 'start': 57, 'eng': "and we'll have time for the good stuff.", 'chn': '然后我们就有时间去做更有意思的事情了。', 'end': 59},
    {'index': '18', 'start': 59, 'eng': "I question the entire premise of this piece, but I'm always interested", 'chn': '我对这个说法持保留意见，不过我还是愿意听听', 'end': 63},
    {'index': '19', 'start': 63, 'eng': "in hearing what they've come up with before they call me.", 'chn': '他们在找我之前有什么想法。', 'end': 66},
    {'index': '20', 'start': 66, 'eng': 'Some of my favorites:', 'chn': '我最喜欢的几个是：', 'end': 67},
    {'index': '21', 'start': 67, 'eng': 'doing errands where you only have to make right-hand turns --', 'chn': '只完成那些只需要右转的事；', 'end': 70},
    {'index': '22', 'start': 70, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 71},
    {'index': '23', 'start': 71, 'eng': 'Being extremely judicious in microwave usage:', 'chn': '在用微波炉时，要极度审慎：', 'end': 73},
    {'index': '24', 'start': 73, 'eng': 'it says three to three-and-a-half minutes on the package,', 'chn': '当食物包装上面写了3到3.5分钟时，', 'end': 76},
    {'index': '25', 'start': 76, 'eng': "we're totally getting in on the bottom side of that.", 'chn': '我们要挑时间最短的那个。', 'end': 79},
    {'index': '26', 'start': 79, 'eng': 'And my personal favorite, which makes sense on some level,', 'chn': '我个人最喜欢的是，录下你最喜欢看的电视剧，', 'end': 81},
    {'index': '27', 'start': 81, 'eng': 'is to DVR your favorite shows so you can fast-forward through the commercials.', 'chn': '然后你就可以跳过广告了。其实在某个程度上，还是挺有道理的。', 'end': 85},
    {'index': '28', 'start': 85, 'eng': 'That way, you save eight minutes every half hour,', 'chn': '这样，你每半个小时就可以挤出八分钟。', 'end': 87},
    {'index': '29', 'start': 87, 'eng': 'so in the course of two hours of watching TV,', 'chn': '那么你葱用来看电视的两个小时中，', 'end': 90},
    {'index': '30', 'start': 90, 'eng': 'you find 32 minutes to exercise.', 'chn': '可以挤出32分钟锻炼的时间。', 'end': 91},
    {'index': '31', 'start': 91, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 92},
    {'index': '32', 'start': 92, 'eng': 'Which is true.', 'chn': '倒的确是这么回事儿。', 'end': 93},
    {'index': '33', 'start': 94, 'eng': 'You know another way to find 32 minutes to exercise?', 'chn': '你还知道其他可以找到32分钟锻炼时间的方法吗？', 'end': 97},
    {'index': '34', 'start': 97, 'eng': "Don't watch two hours of TV a day, right?", 'chn': '不要每天都看两个小时电视就行了，对吧？', 'end': 99},
    {'index': '35', 'start': 99, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 100},
    {'index': '36', 'start': 100, 'eng': "Anyway, the idea is we'll save bits of time here and there, add it up,", 'chn': '总之，就是要在各处都省点时间，', 'end': 104},
    {'index': '37', 'start': 104, 'eng': 'we will finally get to everything we want to do.', 'chn': '加起来就有时间做我们想做的事了。', 'end': 106},
    {'index': '38', 'start': 106, 'eng': 'But after studying how successful people spend their time', 'chn': '但在我了解成功的人如何分配时间，', 'end': 109},
    {'index': '39', 'start': 109, 'eng': 'and looking at their schedules hour by hour,', 'chn': '并看过了他们的时间表后，', 'end': 112},
    {'index': '40', 'start': 112, 'eng': 'I think this idea has it completely backward.', 'chn': '我觉得这个想法是完全本末倒置的。', 'end': 115},
    {'index': '41', 'start': 116, 'eng': "We don't build the lives we want by saving time.", 'chn': '我们不是通过节省时间来打造我们想过的生活。', 'end': 119},
    {'index': '42', 'start': 120, 'eng': 'We build the lives we want,', 'chn': '我们应该先建立我们想要的生活，', 'end': 121},
    {'index': '43', 'start': 122, 'eng': 'and then time saves itself.', 'chn': '时间就会自然而然节省出来。', 'end': 125},
    {'index': '44', 'start': 127, 'eng': "Here's what I mean.", 'chn': '我来解释一下。', 'end': 128},
    {'index': '45', 'start': 128, 'eng': 'I recently did a time diary project', 'chn': '我最近有个时间日记项目，', 'end': 129},
    {'index': '46', 'start': 129, 'eng': 'looking at 1,001 days in the lives of extremely busy women.', 'chn': '观察最忙碌的女士生命中的1001天。', 'end': 134},
    {'index': '47', 'start': 134, 'eng': 'They had demanding jobs, sometimes their own businesses,', 'chn': '她们工作繁忙，有时候是自己的生意，', 'end': 136},
    {'index': '48', 'start': 136, 'eng': 'kids to care for, maybe parents to care for,', 'chn': '有时候要照顾自己的孩子，或者是照顾父母，', 'end': 138},
    {'index': '49', 'start': 138, 'eng': 'community commitments --', 'chn': '还有服务社区等等——', 'end': 140},
    {'index': '50', 'start': 140, 'eng': 'busy, busy people.', 'chn': '都是一些很忙的人。', 'end': 142},
    {'index': '51', 'start': 142, 'eng': 'I had them keep track of their time for a week', 'chn': '我让她们记录了一星期的行程，', 'end': 144},
    {'index': '52', 'start': 144, 'eng': 'so I could add up how much they worked and slept,', 'chn': '计算她们工作和睡觉的时间，', 'end': 147},
    {'index': '53', 'start': 147, 'eng': 'and I interviewed them about their strategies, for my book.', 'chn': '为了我的书，我还采访了解了她们的常用策略。', 'end': 149},
    {'index': '54', 'start': 150, 'eng': 'One of the women whose time log I studied', 'chn': '其中一个被我研究过时间表的女士，', 'end': 152},
    {'index': '55', 'start': 152, 'eng': 'goes out on a Wednesday night for something.', 'chn': '在一个周三晚上出去了一趟，', 'end': 154},
    {'index': '56', 'start': 154, 'eng': 'She comes home to find that her water heater has broken,', 'chn': '回家发现她的热水器坏了，', 'end': 156},
    {'index': '57', 'start': 156, 'eng': 'and there is now water all over her basement.', 'chn': '地下室都被水淹了。', 'end': 159},
    {'index': '58', 'start': 160, 'eng': "If you've ever had anything like this happen to you,", 'chn': '如果你也遇到过这种事儿的话，', 'end': 162},
    {'index': '59', 'start': 162, 'eng': 'you know it is a hugely damaging, frightening, sopping mess.', 'chn': '你会知道眼前的景象多么令人崩溃和沮丧。', 'end': 165},
    {'index': '60', 'start': 165, 'eng': "So she's dealing with the immediate aftermath that night,", 'chn': '于是那个晚上她立刻着手处理，', 'end': 168},
    {'index': '61', 'start': 168, 'eng': "next day she's got plumbers coming in,", 'chn': '第二天她找了一个水管工，', 'end': 170},
    {'index': '62', 'start': 170, 'eng': 'day after that, professional cleaning crew dealing with the ruined carpet.', 'chn': '第三天找了专业的清理人员来处理损坏的地毯。', 'end': 173},
    {'index': '63', 'start': 173, 'eng': 'All this is being recorded on her time log.', 'chn': '所有这些都算在了她的时间表内。', 'end': 175},
    {'index': '64', 'start': 175, 'eng': 'Winds up taking seven hours of her week.', 'chn': '总共花了她一周中的七个小时。', 'end': 178},
    {'index': '65', 'start': 179, 'eng': 'Seven hours.', 'chn': '七个小时。', 'end': 180},
    {'index': '66', 'start': 180, 'eng': "That's like finding an extra hour in the day.", 'chn': '这就等于一周七天每天都要挤出一个小时。', 'end': 183},
    {'index': '67', 'start': 184, 'eng': "But I'm sure if you had asked her at the start of the week,", 'chn': '但是假如你在这一周刚开始时就问她，', 'end': 187},
    {'index': '68', 'start': 187, 'eng': '"Could you find seven hours to train for a triathlon?"', 'chn': '“你能在这周抽出七个小时来参加铁人三项吗？”，', 'end': 190},
    {'index': '69', 'start': 191, 'eng': '"Could you find seven hours to mentor seven worthy people?"', 'chn': '“你能在这周抽出七个小时指导七个有潜力的人吗？“', 'end': 195},
    {'index': '70', 'start': 195, 'eng': "I'm sure she would've said what most of us would've said,", 'chn': '我确定她会像大多数人一样，', 'end': 198},
    {'index': '71', 'start': 198, 'eng': 'which is, "No -- can\'t you see how busy I am?"', 'chn': '说，”怎么可能，你看不出我有多忙吗？“', 'end': 202},
    {'index': '72', 'start': 203, 'eng': 'Yet when she had to find seven hours', 'chn': '但是她最后不得不抽出七个小时，', 'end': 205},
    {'index': '73', 'start': 205, 'eng': 'because there is water all over her basement,', 'chn': '因为她的地下室都被水淹了，', 'end': 207},
    {'index': '74', 'start': 207, 'eng': 'she found seven hours.', 'chn': '她挤出了这七个小时。', 'end': 210},
    {'index': '75', 'start': 210, 'eng': 'And what this shows us is that time is highly elastic.', 'chn': '这件事告诉我们：时间是有弹性的。', 'end': 215},
    {'index': '76', 'start': 215, 'eng': 'We cannot make more time,', 'chn': '我们不能创造更多时间，', 'end': 217},
    {'index': '77', 'start': 217, 'eng': 'but time will stretch to accommodate what we choose to put into it.', 'chn': '但是时间会自己调整去适应我们选择去做的事情。', 'end': 221},
    {'index': '78', 'start': 222, 'eng': 'And so the key to time management', 'chn': '所以时间管理的关键就是', 'end': 224},
    {'index': '79', 'start': 225, 'eng': 'is treating our priorities', 'chn': '对待最重要的事情应该像', 'end': 227},
    {'index': '80', 'start': 227, 'eng': 'as the equivalent of that broken water heater.', 'chn': '对待那个坏了的热水器一样。', 'end': 230},
    {'index': '81', 'start': 231, 'eng': 'To get at this,', 'chn': '要做到这一点，', 'end': 233},
    {'index': '82', 'start': 233, 'eng': 'I like to use language from one of the busiest people I ever interviewed.', 'chn': '我要借用我采访过最忙的人的话。', 'end': 236},
    {'index': '83', 'start': 236, 'eng': 'By busy, I mean she was running a small business', 'chn': '她经营着一个小企业，', 'end': 238},
    {'index': '84', 'start': 238, 'eng': 'with 12 people on the payroll,', 'chn': '请了十二名员工，', 'end': 240},
    {'index': '85', 'start': 240, 'eng': 'she had six children in her spare time.', 'chn': '空余时间她还要照顾六个孩子。', 'end': 242},
    {'index': '86', 'start': 242, 'eng': 'I was getting in touch with her to set up an interview', 'chn': '我联系上了她，想要采访她关于', 'end': 245},
    {'index': '87', 'start': 245, 'eng': 'on how she "had it all" -- that phrase.', 'chn': '她是怎么做到“无所不能”的。', 'end': 247},
    {'index': '88', 'start': 247, 'eng': 'I remember it was a Thursday morning,', 'chn': '我记得那是一个星期四的早晨，', 'end': 249},
    {'index': '89', 'start': 249, 'eng': 'and she was not available to speak with me.', 'chn': '她没时间和我说话。', 'end': 251},
    {'index': '90', 'start': 251, 'eng': 'Of course, right?', 'chn': '当然了，她很忙。', 'end': 252},
    {'index': '91', 'start': 252, 'eng': 'But the reason she was unavailable to speak with me', 'chn': '但是她没时间和我说话的原因是，', 'end': 255},
    {'index': '92', 'start': 255, 'eng': 'is that she was out for a hike,', 'chn': '她去远足了。', 'end': 257},
    {'index': '93', 'start': 257, 'eng': 'because it was a beautiful spring morning,', 'chn': '因为那是春季一个美丽的清晨，', 'end': 259},
    {'index': '94', 'start': 259, 'eng': 'and she wanted to go for a hike.', 'chn': '所以她去远足了。', 'end': 260},
    {'index': '95', 'start': 260, 'eng': 'So of course this makes me even more intrigued,', 'chn': '这样的她让我变得更感兴趣了，', 'end': 263},
    {'index': '96', 'start': 263, 'eng': 'and when I finally do catch up with her, she explains it like this.', 'chn': '当我最终联系上她时，', 'end': 266},
    {'index': '97', 'start': 266, 'eng': 'She says, "Listen Laura, everything I do,', 'chn': '她说：“听我说，劳拉，我做的所有的事情，', 'end': 268},
    {'index': '98', 'start': 269, 'eng': 'every minute I spend, is my choice."', 'chn': '我花的每分每秒，都是我的选择。”', 'end': 273},
    {'index': '99', 'start': 273, 'eng': 'And rather than say,', 'chn': '所以与其说，', 'end': 274},
    {'index': '100', 'start': 274, 'eng': '"I don\'t have time to do x, y or z,"', 'chn': '”我没有时间做这个，这个，或者那个。”', 'end': 277},
    {'index': '101', 'start': 277, 'eng': 'she\'d say, "I don\'t do x, y or z because it\'s not a priority."', 'chn': '她会说：”我不做这些事情因为这些不是我的首要任务。“', 'end': 282},
    {'index': '102', 'start': 283, 'eng': '"I don\'t have time," often means "It\'s not a priority."', 'chn': '“我没有时间”的意思通常是”那不是我的首要任务”。', 'end': 287},
    {'index': '103', 'start': 288, 'eng': "If you think about it, that's really more accurate language.", 'chn': '其实你想想，那的确是更准确的说法。', 'end': 291},
    {'index': '104', 'start': 291, 'eng': "I could tell you I don't have time to dust my blinds,", 'chn': '我可能会告诉你我没有时间清理百叶窗，', 'end': 294},
    {'index': '105', 'start': 294, 'eng': "but that's not true.", 'chn': '但那不是真的。', 'end': 295},
    {'index': '106', 'start': 295, 'eng': 'If you offered to pay me $100,000 to dust my blinds,', 'chn': '假如你愿意付我10万美金让我给百叶窗除尘，', 'end': 298},
    {'index': '107', 'start': 298, 'eng': 'I would get to it pretty quickly.', 'chn': '我会马上就去做。', 'end': 299},
    {'index': '108', 'start': 299, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 300},
    {'index': '109', 'start': 300, 'eng': 'Since that is not going to happen,', 'chn': '既然那不可能发生，', 'end': 302},
    {'index': '110', 'start': 302, 'eng': 'I can acknowledge this is not a matter of lacking time;', 'chn': '我可以说不是因为时间不够，', 'end': 304},
    {'index': '111', 'start': 305, 'eng': "it's that I don't want to do it.", 'chn': '而是我不想做。', 'end': 306},
    {'index': '112', 'start': 306, 'eng': 'Using this language reminds us that time is a choice.', 'chn': '这么说提醒了我们，时间是一种选择。', 'end': 310},
    {'index': '113', 'start': 310, 'eng': 'And granted,', 'chn': '我会告诉你，', 'end': 311},
    {'index': '114', 'start': 311, 'eng': 'there may be horrible consequences for making different choices,', 'chn': '当然，不同的选择有时候会', 'end': 314},
    {'index': '115', 'start': 314, 'eng': 'I will give you that.', 'chn': '带来可怕的后果。', 'end': 315},
    {'index': '116', 'start': 315, 'eng': 'But we are smart people,', 'chn': '但是我们都是聪明人，', 'end': 317},
    {'index': '117', 'start': 317, 'eng': 'and certainly over the long run,', 'chn': '从长远来看，', 'end': 319},
    {'index': '118', 'start': 319, 'eng': 'we have the power to fill our lives', 'chn': '我们有能力去选择一些值得做的事，', 'end': 321},
    {'index': '119', 'start': 321, 'eng': 'with the things that deserve to be there.', 'chn': '来填补我们生命中的时间。', 'end': 323},
    {'index': '120', 'start': 325, 'eng': 'So how do we do that?', 'chn': '那么我们应该怎么做呢？', 'end': 326},
    {'index': '121', 'start': 326, 'eng': 'How do we treat our priorities', 'chn': '我们要如何像对待那个', 'end': 328},
    {'index': '122', 'start': 328, 'eng': 'as the equivalent of that broken water heater?', 'chn': '坏了的热水器一样对待我们的首要任务？', 'end': 330},
    {'index': '123', 'start': 331, 'eng': 'Well, first we need to figure out what they are.', 'chn': '首先，我们需要找出哪些事最重要。', 'end': 333},
    {'index': '124', 'start': 333, 'eng': 'I want to give you two strategies for thinking about this.', 'chn': '我想给你们分享两个技巧。', 'end': 336},
    {'index': '125', 'start': 336, 'eng': 'The first, on the professional side:', 'chn': '第一个，从职业的角度来说：', 'end': 338},
    {'index': '126', 'start': 338, 'eng': "I'm sure many people coming up to the end of the year", 'chn': '我相信许多人在年底的时候', 'end': 340},
    {'index': '127', 'start': 340, 'eng': 'are giving or getting annual performance reviews.', 'chn': '会发出或者收到年度绩效审查。', 'end': 343},
    {'index': '128', 'start': 343, 'eng': 'You look back over your successes over the year,', 'chn': '你回头看看这一年的成功和', 'end': 345},
    {'index': '129', 'start': 345, 'eng': 'your "opportunities for growth."', 'chn': '“成长的机会”。', 'end': 347},
    {'index': '130', 'start': 347, 'eng': 'And this serves its purpose,', 'chn': '这的确起到了它的作用，', 'end': 349},
    {'index': '131', 'start': 350, 'eng': "but I find it's more effective to do this looking forward.", 'chn': '但是我发现往前看会更有效。', 'end': 352},
    {'index': '132', 'start': 352, 'eng': "So I want you to pretend it's the end of next year.", 'chn': '我想让你们把这当做下一年的年底。', 'end': 355},
    {'index': '133', 'start': 356, 'eng': "You're giving yourself a performance review,", 'chn': '你在给自己做年度绩效审查，', 'end': 358},
    {'index': '134', 'start': 358, 'eng': 'and it has been an absolutely amazing year for you professionally.', 'chn': '在专业方面，这一年的表现非常出众。', 'end': 363},
    {'index': '135', 'start': 363, 'eng': 'What three to five things did you do that made it so amazing?', 'chn': '是哪三到五件事使这一年变得如此出众？', 'end': 369},
    {'index': '136', 'start': 370, 'eng': "So you can write next year's performance review now.", 'chn': '你现在就可以写明年的绩效审查。', 'end': 374},
    {'index': '137', 'start': 374, 'eng': 'And you can do this for your personal life, too.', 'chn': '你也可以在个人生活方面这么做。', 'end': 376},
    {'index': '138', 'start': 376, 'eng': "I'm sure many of you, like me, come December,", 'chn': '我相信你们许多人，包括我，在十二月，', 'end': 379},
    {'index': '139', 'start': 379, 'eng': 'get cards that contain these folded up sheets of colored paper,', 'chn': '都会收到这种夹着彩色纸的卡片。', 'end': 382},
    {'index': '140', 'start': 383, 'eng': 'on which is written what is known as the family holiday letter.', 'chn': '上面写着“家庭假日信件”。', 'end': 388},
    {'index': '141', 'start': 388, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 389},
    {'index': '142', 'start': 389, 'eng': 'Bit of a wretched genre of literature, really,', 'chn': '听起来像是一个挺悲惨的文学题材，', 'end': 392},
    {'index': '143', 'start': 392, 'eng': 'going on about how amazing everyone in the household is,', 'chn': '谈论家里每个人有多了不起，', 'end': 395},
    {'index': '144', 'start': 395, 'eng': 'or even more scintillating,', 'chn': '或者更精彩点，', 'end': 397},
    {'index': '145', 'start': 397, 'eng': 'how busy everyone in the household is.', 'chn': '家里每个人有多忙。', 'end': 399},
    {'index': '146', 'start': 399, 'eng': 'But these letters serve a purpose,', 'chn': '但是这些信有它们的用处，', 'end': 401},
    {'index': '147', 'start': 401, 'eng': 'which is that they tell your friends and family', 'chn': '它们告诉你的朋友和家人', 'end': 403},
    {'index': '148', 'start': 403, 'eng': 'what you did in your personal life that mattered to you over the year.', 'chn': '你这一年里做了什么对个人生活有意义的事。', 'end': 406},
    {'index': '149', 'start': 406, 'eng': "So this year's kind of done,", 'chn': '那么今年快要结束了，', 'end': 408},
    {'index': '150', 'start': 408, 'eng': "but I want you to pretend it's the end of next year,", 'chn': '我想让你假装这是明年的年底，', 'end': 410},
    {'index': '151', 'start': 410, 'eng': 'and it has been an absolutely amazing year', 'chn': '对你和你在乎的人来说，', 'end': 413},
    {'index': '152', 'start': 413, 'eng': 'for you and the people you care about.', 'chn': '这都是无与伦比的一年。', 'end': 416},
    {'index': '153', 'start': 417, 'eng': 'What three to five things did you do that made it so amazing?', 'chn': '哪三到五件事让你这一年表现如此出色？', 'end': 421},
    {'index': '154', 'start': 422, 'eng': "So you can write next year's family holiday letter now.", 'chn': '其实你现在就可以写明年的家庭假日信件了。', 'end': 426},
    {'index': '155', 'start': 427, 'eng': "Don't send it.", 'chn': '先不要发出去。', 'end': 428},
    {'index': '156', 'start': 428, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 429},
    {'index': '157', 'start': 429, 'eng': "Please, don't send it.", 'chn': '真的，不要发出去。', 'end': 432},
    {'index': '158', 'start': 432, 'eng': 'But you can write it.', 'chn': '但是你可以写。', 'end': 434},
    {'index': '159', 'start': 434, 'eng': 'And now, between the performance review and the family holiday letter,', 'chn': '现在，有了绩效评估和写给家人的信，', 'end': 437},
    {'index': '160', 'start': 438, 'eng': 'we have a list of six to ten goals we can work on in the next year.', 'chn': '我们就有了六到十个明年可以努力的目标。', 'end': 441},
    {'index': '161', 'start': 441, 'eng': 'And now we need to break these down into doable steps.', 'chn': '我们需要先把他们分成可行的阶段性任务。', 'end': 444},
    {'index': '162', 'start': 444, 'eng': 'So maybe you want to write a family history.', 'chn': '或许你要写一个家族传记。', 'end': 446},
    {'index': '163', 'start': 446, 'eng': 'First, you can read some other family histories,', 'chn': '首先，你可以读读别人的家族历史，', 'end': 448},
    {'index': '164', 'start': 448, 'eng': 'get a sense for the style.', 'chn': '了解一下大概的风格。', 'end': 449},
    {'index': '165', 'start': 449, 'eng': 'Then maybe think about the questions you want to ask your relatives,', 'chn': '然后可以想象你要问亲戚的问题，', 'end': 453},
    {'index': '166', 'start': 453, 'eng': 'set up appointments to interview them.', 'chn': '约定和他们见面谈话的时间。', 'end': 454},
    {'index': '167', 'start': 455, 'eng': 'Or maybe you want to run a 5K.', 'chn': '或者你想要参加一个五千米的短程马拉松。', 'end': 456},
    {'index': '168', 'start': 456, 'eng': 'So you need to find a race and sign up, figure out a training plan,', 'chn': '你需要先找一个竞赛报名，再做一个培训计划，', 'end': 459},
    {'index': '169', 'start': 459, 'eng': 'and dig those shoes out of the back of the closet.', 'chn': '从衣柜底下翻出你的运动鞋。', 'end': 462},
    {'index': '170', 'start': 462, 'eng': 'And then -- this is key --', 'chn': '然后——这是关键——', 'end': 464},
    {'index': '171', 'start': 464, 'eng': 'we treat our priorities as the equivalent of that broken water heater,', 'chn': '我们将我们的首要事件视为那个坏掉的热水器，', 'end': 468},
    {'index': '172', 'start': 468, 'eng': 'by putting them into our schedules first.', 'chn': '将它们优先放入我们的日程表里。', 'end': 471},
    {'index': '173', 'start': 471, 'eng': 'We do this by thinking through our weeks before we are in them.', 'chn': '我们要在事情发生的几周前就先想好。', 'end': 476},
    {'index': '174', 'start': 476, 'eng': 'I find a really good time to do this is Friday afternoons.', 'chn': '我发现周五的下午最适合处理这事儿。', 'end': 480},
    {'index': '175', 'start': 480, 'eng': 'Friday afternoon is what an economist might call', 'chn': '周五的下午是被经济学家称为', 'end': 483},
    {'index': '176', 'start': 483, 'eng': 'a "low opportunity cost" time.', 'chn': '“低机会成本”时间。', 'end': 485},
    {'index': '177', 'start': 486, 'eng': 'Most of us are not sitting there on Friday afternoons saying,', 'chn': '我们大部分人不会在周五下午想着，', 'end': 489},
    {'index': '178', 'start': 489, 'eng': '"I am excited to make progress', 'chn': '“我要朝我的个人和', 'end': 491},
    {'index': '179', 'start': 491, 'eng': 'toward my personal and professional priorities', 'chn': '职业生涯的首要事件迈进了，', 'end': 493},
    {'index': '180', 'start': 493, 'eng': 'right now."', 'chn': '所以很兴奋。“', 'end': 494},
    {'index': '181', 'start': 494, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 495},
    {'index': '182', 'start': 495, 'eng': 'But we are willing to think about what those should be.', 'chn': '但是我们愿意去想那些事是什么。', 'end': 498},
    {'index': '183', 'start': 498, 'eng': 'So take a little bit of time Friday afternoon,', 'chn': '所以在周五下午花一点时间，', 'end': 500},
    {'index': '184', 'start': 500, 'eng': 'make yourself a three-category priority list: career, relationships, self.', 'chn': '为自己做一个分成三类的首要事件的列表：事业，人际关系，个人。', 'end': 507},
    {'index': '185', 'start': 508, 'eng': 'Making a three-category list reminds us', 'chn': '这样的三项分类列表提醒了我们', 'end': 511},
    {'index': '186', 'start': 511, 'eng': 'that there should be something in all three categories.', 'chn': '每一个类别都应该有一些事。', 'end': 514},
    {'index': '187', 'start': 514, 'eng': 'Career, we think about;', 'chn': '事业，我们经常考虑；', 'end': 516},
    {'index': '188', 'start': 516, 'eng': 'relationships, self --', 'chn': '人际关系，个人——', 'end': 517},
    {'index': '189', 'start': 517, 'eng': 'not so much.', 'chn': '很少会想。', 'end': 519},
    {'index': '190', 'start': 519, 'eng': 'But anyway, just a short list,', 'chn': '无论如何，只要一个短短的列表，', 'end': 520},
    {'index': '191', 'start': 521, 'eng': 'two to three items in each.', 'chn': '每个都包含两到三件事。', 'end': 522},
    {'index': '192', 'start': 522, 'eng': 'Then look out over the whole of the next week,', 'chn': '它们会帮助我们看清下周，', 'end': 525},
    {'index': '193', 'start': 525, 'eng': 'and see where you can plan them in.', 'chn': '如何在下周计划这些事情。', 'end': 526},
    {'index': '194', 'start': 527, 'eng': 'Where you plan them in is up to you.', 'chn': '你可以决定如何计划。', 'end': 530},
    {'index': '195', 'start': 530, 'eng': 'I know this is going to be more complicated for some people than others.', 'chn': '这可能对一些人来说会比较困难一点。', 'end': 533},
    {'index': '196', 'start': 533, 'eng': "I mean, some people's lives are just harder than others.", 'chn': '我的意思是，有些人的人生就是比较复杂。', 'end': 537},
    {'index': '197', 'start': 537, 'eng': 'It is not going to be easy to find time to take that poetry class', 'chn': '如果你自己有好几个要照顾的小孩，', 'end': 540},
    {'index': '198', 'start': 540, 'eng': 'if you are caring for multiple children on your own.', 'chn': '想要找时间去参加诗歌班一定不容易。', 'end': 543},
    {'index': '199', 'start': 543, 'eng': 'I get that.', 'chn': '我懂。', 'end': 545},
    {'index': '200', 'start': 545, 'eng': "And I don't want to minimize anyone's struggle.", 'chn': '我不想轻视任何人的困难。', 'end': 547},
    {'index': '201', 'start': 547, 'eng': 'But I do think that the numbers I am about to tell you are empowering.', 'chn': '当是我觉得我接下来要说的数字是会改变你的想法的。', 'end': 551},
    {'index': '202', 'start': 552, 'eng': 'There are 168 hours in a week.', 'chn': '我们每周都有168个小时。', 'end': 556},
    {'index': '203', 'start': 557, 'eng': 'Twenty-four times seven is 168 hours.', 'chn': '24乘以7是168个小时。', 'end': 562},
    {'index': '204', 'start': 563, 'eng': 'That is a lot of time.', 'chn': '这是一段很长时间。', 'end': 565},
    {'index': '205', 'start': 566, 'eng': 'If you are working a full-time job, so 40 hours a week,', 'chn': '假如你有一个全职的工作，一周是40个小时，', 'end': 569},
    {'index': '206', 'start': 569, 'eng': 'sleeping eight hours a night, so 56 hours a week --', 'chn': '每晚睡八个小时，一周是56个小时，', 'end': 572},
    {'index': '207', 'start': 572, 'eng': 'that leaves 72 hours for other things.', 'chn': '我们有剩下72个小时来做其他事情。', 'end': 575},
    {'index': '208', 'start': 576, 'eng': 'That is a lot of time.', 'chn': '这是一段很长的时间。', 'end': 578},
    {'index': '209', 'start': 578, 'eng': "You say you're working 50 hours a week,", 'chn': '假如你说你每周工作50个小时，', 'end': 580},
    {'index': '210', 'start': 580, 'eng': 'maybe a main job and a side hustle.', 'chn': '比如一份全职和一份兼职。', 'end': 582},
    {'index': '211', 'start': 582, 'eng': 'Well, that leaves 62 hours for other things.', 'chn': '这样你还是有60小时去做其他的事情。', 'end': 585},
    {'index': '212', 'start': 585, 'eng': "You say you're working 60 hours.", 'chn': '假如你说你每周工作60个小时，', 'end': 587},
    {'index': '213', 'start': 587, 'eng': 'Well, that leaves 52 hours for other things.', 'chn': '你还是有52个小时去做其他的事情。', 'end': 589},
    {'index': '214', 'start': 589, 'eng': "You say you're working more than 60 hours.", 'chn': '你说你每周工作超过60个小时，', 'end': 591},
    {'index': '215', 'start': 591, 'eng': 'Well, are you sure?', 'chn': '你确定吗？', 'end': 593},
    {'index': '216', 'start': 593, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 594},
    {'index': '217', 'start': 594, 'eng': "There was once a study comparing people's estimated work weeks", 'chn': '曾经有一个研究对比了人们估计的工作时间，', 'end': 597},
    {'index': '218', 'start': 597, 'eng': 'with time diaries.', 'chn': '和实际的工作日记。', 'end': 599},
    {'index': '219', 'start': 599, 'eng': 'They found that people claiming 75-plus-hour work weeks', 'chn': '他们发现那些表示工作超过75小时的人，', 'end': 601},
    {'index': '220', 'start': 601, 'eng': 'were off by about 25 hours.', 'chn': '有25小时的误差。', 'end': 604},
    {'index': '221', 'start': 604, 'eng': '(Laughter)', 'chn': '（笑声）', 'end': 605},
    {'index': '222', 'start': 605, 'eng': 'You can guess in which direction, right?', 'chn': '你可以猜到这个误差是多了还是少了吧？', 'end': 608},
    {'index': '223', 'start': 609, 'eng': 'Anyway, in 168 hours a week,', 'chn': '无论如何，在一周的168个小时里，', 'end': 611},
    {'index': '224', 'start': 611, 'eng': 'I think we can find time for what matters to you.', 'chn': '我觉得我们总可以找到时间做我们想做的事。', 'end': 614},
    {'index': '225', 'start': 614, 'eng': 'If you want to spend more time with your kids,', 'chn': '如果你想花时间陪陪你的孩子，', 'end': 616},
    {'index': '226', 'start': 616, 'eng': "you want to study more for a test you're taking,", 'chn': '或者准备你即将到来的考试，', 'end': 619},
    {'index': '227', 'start': 619, 'eng': 'you want to exercise for three hours and volunteer for two,', 'chn': '你想锻炼两三个小时或者做两个小时志愿者，', 'end': 622},
    {'index': '228', 'start': 622, 'eng': 'you can.', 'chn': '你都可以的。', 'end': 623},
    {'index': '229', 'start': 623, 'eng': "And that's even if you're working way more than full-time hours.", 'chn': '即便你的工作时间远超过法定时间。', 'end': 627},
    {'index': '230', 'start': 627, 'eng': 'So we have plenty of time, which is great,', 'chn': '所以我们有很多时间，这很好。', 'end': 629},
    {'index': '231', 'start': 629, 'eng': 'because guess what?', 'chn': '但是你知道吗？', 'end': 631},
    {'index': '232', 'start': 631, 'eng': "We don't even need that much time to do amazing things.", 'chn': '我们根本不需要那么多时间去完成一个大目标。', 'end': 633},
    {'index': '233', 'start': 634, 'eng': 'But when most of us have bits of time, what do we do?', 'chn': '但当我们有一点空闲时间的时候，我们会做什么？', 'end': 637},
    {'index': '234', 'start': 637, 'eng': 'Pull out the phone, right?', 'chn': '拿出手机，是吧？', 'end': 639},
    {'index': '235', 'start': 639, 'eng': 'Start deleting emails.', 'chn': '开始删除邮件。', 'end': 641},
    {'index': '236', 'start': 642, 'eng': "Otherwise, we're puttering around the house", 'chn': '或者在家里闲逛，', 'end': 644},
    {'index': '237', 'start': 644, 'eng': 'or watching TV.', 'chn': '看电视。', 'end': 645},
    {'index': '238', 'start': 645, 'eng': 'But small moments can have great power.', 'chn': '但是每个不起眼的时刻都潜力无限。', 'end': 648},
    {'index': '239', 'start': 649, 'eng': 'You can use your bits of time', 'chn': '你可以用零星的时间，', 'end': 651},
    {'index': '240', 'start': 651, 'eng': 'for bits of joy.', 'chn': '来获得零星的快乐。', 'end': 654},
    {'index': '241', 'start': 655, 'eng': "Maybe it's choosing to read something wonderful on the bus", 'chn': '比如说在去上班的公车上', 'end': 657},
    {'index': '242', 'start': 657, 'eng': 'on the way to work.', 'chn': '读一些精彩的东西。', 'end': 659},
    {'index': '243', 'start': 659, 'eng': 'I know when I had a job that required two bus rides', 'chn': '当我以前的工作需要我每天早上乘两趟公车', 'end': 661},
    {'index': '244', 'start': 661, 'eng': 'and a subway ride every morning,', 'chn': '和一趟地铁的时候，', 'end': 663},
    {'index': '245', 'start': 663, 'eng': 'I used to go to the library on weekends to get stuff to read.', 'chn': '我周末会去图书馆找东西来读。', 'end': 666},
    {'index': '246', 'start': 666, 'eng': 'It made the whole experience almost, almost, enjoyable.', 'chn': '这几乎，几乎让我的生活更丰富了。', 'end': 670},
    {'index': '247', 'start': 671, 'eng': 'Breaks at work can be used for meditating or praying.', 'chn': '工作间隙的休息时间可以用来冥想或者祷告。', 'end': 674},
    {'index': '248', 'start': 675, 'eng': 'If family dinner is out because of your crazy work schedule,', 'chn': '如果你因为工作忙而不能吃家庭晚餐，', 'end': 678},
    {'index': '249', 'start': 678, 'eng': 'maybe family breakfast could be a good substitute.', 'chn': '试一下家庭早餐。', 'end': 681},
    {'index': '250', 'start': 681, 'eng': "It's about looking at the whole of one's time", 'chn': '这就是看着一个人所有的时间，', 'end': 684},
    {'index': '251', 'start': 684, 'eng': 'and seeing where the good stuff can go.', 'chn': '然后找到什么时候可以做想做的事。', 'end': 686},
    {'index': '252', 'start': 688, 'eng': 'I truly believe this.', 'chn': '我真的相信，', 'end': 690},
    {'index': '253', 'start': 690, 'eng': 'There is time.', 'chn': '我们都有充分的时间。', 'end': 693},
    {'index': '254', 'start': 694, 'eng': 'Even if we are busy,', 'chn': '就算我们很忙，', 'end': 696},
    {'index': '255', 'start': 697, 'eng': 'we have time for what matters.', 'chn': '我们仍然有时间去做重要的事。', 'end': 698},
    {'index': '256', 'start': 699, 'eng': 'And when we focus on what matters,', 'chn': '当我们关注在重要的事上时，', 'end': 701},
    {'index': '257', 'start': 702, 'eng': 'we can build the lives we want', 'chn': '我们可以用所拥有的时间', 'end': 703},
    {'index': '258', 'start': 704, 'eng': "in the time we've got.", 'chn': '创造我们想要的生活。', 'end': 705},
    {'index': '259', 'start': 706, 'eng': 'Thank you.', 'chn': '谢谢。', 'end': 707},
    {'index': '260', 'start': 707, 'eng': '(Applause)', 'chn': '（鼓掌）', 'end': 712}
];